apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-pipelines

resources:
  - tasks/test.yaml
  - tasks/build-and-push.yaml
  - tasks/git-clone.yaml
  - pipeline.yaml
  - rbac/pipeline-runner.yaml
  - triggers/cronjob.yaml
  - credentials/harbor-secret.yaml