apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-calculator
  namespace: tekton-pipelines

spec:
  params:
    - name: git-url
      type: string

    - name: git-revision
      type: string

    - name: version
      type: string

    - name: image-repository
      type: string

    - name: image-tag
      type: string

    - name: context
      type: string
      default: go-calculator

  workspaces:
    - name: source

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone

      params:
        - name: url
          value: $(params.git-url)

        - name: revision
          value: $(params.git-revision)

        - name: deleteExisting
          value: "true"

      workspaces:
        - name: output
          workspace: source

    - name: test
      runAfter:
        - fetch-source

      taskRef:
        name: go-test

      params:
        - name: context
          value: "$(params.context)"

      workspaces:
        - name: source
          workspace: source

    - name: build-and-push
      runAfter:
        - fetch-source

      taskRef:
        name: build-and-push

      params:
        - name: IMAGE
          value: $(params.image-repository)

        - name: VERSION
          value: $(params.version)

        - name: GIT_REVISION
          value: $(params.git-revision)

        - name: CONTEXT
          value: $(params.context)

      workspaces:
        - name: source
          workspace: source