apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines

spec:
  params:
    - name: IMAGE
      type: string
      description: Full image name including tag

    - name: VERSION
      type: string
      description: Application version

    - name: GIT_REVISION
      type: string
      description: Git revision

    - name: CONTEXT
      type: string
      default: go-calculator

  workspaces:
    - name: source

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      args:
        - --dockerfile=$(workspaces.source.path)/$(params.CONTEXT)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --label=org.opencontainers.image.version=$(params.VERSION)
        - --label=org.opencontainers.image.revision=$(params.GIT_REVISION)
        - --cache=true