apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-test
  namespace: tekton-pipelines

spec:
  workspaces:
    - name: source

  steps:
    - name: test
      image: golang:1.25-alpine

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      workingDir: $(workspaces.source.path)/go-calculator

      script: |
        #!/bin/sh
        set -eu

        echo "Running Go tests..."

        go test ./...

        echo "Tests passed."