apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: tekton-privileged
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.harbor.svc.cluster.local": {
          "username": "admin",
          "password": "admin123"
        }
      }
    }
