apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: tekton-pipelines

  profile: all

  pruner:
    disabled: true
    resources:
      - taskrun
      - pipelinerun
    keep: 3

  tektonpruner:
    disabled: true
    global-config:
      enforcedConfigLevel: global

  scheduler:
    disabled: true