apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: tekton-privileged
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.harbor.svc.cluster.local": {
          "auth": "YWRtaW46YWRtaW4xMjM="
        }
      }
    }