---
- name: Delete Argo CD
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Delete Argo CD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ argocd_namespace }}"
        state: absent
        wait: true
        wait_timeout: 300
        wait_sleep: 5
