apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-operator
  namespace: argocd

spec:
  project: default

  source:
    repoURL: ghcr.io/tektoncd/operator/charts
    chart: tekton-operator
    targetRevision: 0.81.0

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true