patches:
  - target:
      kind: Deployment
      name: go-calculator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: go-calculator
      spec:
        template:
          spec:
            containers:
              - name: go-calculator
                env:
                  - name: ENV
                    value: "prod"
                  - name: THEME_COLOR
                    value: "#22c55e"