- name: Create Argo CD namespace
  kubernetes.core.k8s:
    name: "{{ argocd_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install Argo CD
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    src: "https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml"

- name: Wait for Argo CD server
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: argocd-server
    namespace: "{{ argocd_namespace }}"
  register: argocd_server
  until:
    - argocd_server.resources | length > 0
    - argocd_server.resources[0].status.readyReplicas | default(0) | int > 0
  retries: 30
  delay: 5

- name: Generate Argo CD admin password hash
  ansible.builtin.command:
    cmd: >
      {{ ansible_playbook_python }} -c
      "import bcrypt;
      print(bcrypt.hashpw(b'{{ argocd_admin_password }}', bcrypt.gensalt()).decode())"
  register: argocd_password_hash
  changed_when: false
  no_log: true

- name: Configure Argo CD admin password
  kubernetes.core.k8s:
    state: patched
    api_version: v1
    kind: Secret
    name: argocd-secret
    namespace: "{{ argocd_namespace }}"
    definition:
      stringData:
        admin.password: "{{ argocd_password_hash.stdout }}"
        admin.passwordMtime: "2026-09-05T00:00:00Z"
  no_log: true


- name: Create Argo CD root application
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: root
        namespace: "{{ argocd_namespace }}"
      spec:
        project: default

        source:
          repoURL: "{{ argocd_repo_url }}"
          targetRevision: "{{ argocd_repo_revision }}"
          path: "{{ argocd_apps_path }}"

        destination:
          server: https://kubernetes.default.svc
          namespace: "{{ argocd_namespace }}"

        syncPolicy:
          automated:
            prune: true
            selfHeal: true