apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-calculator-pipeline
  namespace: tekton-pipelines
imagePullSecrets:
  - name: harbor-credentials

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-calculator-poller
  namespace: tekton-pipelines

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-calculator-poller
  namespace: tekton-pipelines
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-calculator-poller
  namespace: tekton-pipelines

subjects:
  - kind: ServiceAccount
    name: go-calculator-poller
    namespace: tekton-pipelines

roleRef:
  kind: Role
  name: go-calculator-poller
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-calculator-poller
  namespace: tekton-build
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-calculator-poller
  namespace: tekton-build
subjects:
  - kind: ServiceAccount
    name: go-calculator-poller
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-calculator-poller